#!/usr/bin/env python

import sys

# For Python 2
# from itertools import izip

extra_vars = None
extra_vars_comes_next = False

for arg in sys.argv:
    if arg == '-e':
        extra_vars_comes_next = True
        continue
    elif arg.startswith('--extra-vars='):
        extra_vars = arg[13:]
    elif extra_vars_comes_next:
        extra_vars = arg
    extra_vars_comes_next = False

# If no -e or --extra_vars, the arguments passed the following checks
if extra_vars is None:
    print('INFO: No -e or --extra_vars')
    exit(0)

# c.f. http://stackoverflow.com/questions/5389507/iterating-over-every-two-elements-in-a-list
def grouped(iterable, n):
    return zip(*[iter(iterable)]*n)

allowed_names = ['version', 'disable_batch1']

for vars in extra_vars.split(' '):
    if vars.count('=') != 1:
        print('Invalid extra-var format: {}'.format(vars))
        exit(1)
    
    for name, value in grouped(vars.split('='), 2):
        print(name)
        print(value)
        if not (name in allowed_names):
            print('extra-var {} is not allowed.'.format(name))
            exit(1)

print('All extra-vars are allowed.')
exit(0)


