---
- hosts: localhost
  connection: local
  vars:
    allowed4: default_value4
    denied5: default_value5
  tasks:
    - name: Print variable 'allowed4'
      debug: msg={{ allowed4 }}
    - name: Print variable 'denied5'
      debug: msg={{ denied5 }}
