---
- hosts: localhost
  connection: local
  vars:
    allowed1: default_value1
    allowed2: default_value2
    denied3: default_value3
  tasks:
    - name: Print variable 'allowed1'
      debug: msg={{ allowed1 }}
    - name: Print variable 'allowed2'
      debug: msg={{ allowed2 }}
    - name: Print variable 'denied3'
      debug: msg={{ denied3 }}
